### ISSUE TITLE
Nested gaps does not work.

### ISSUE THREAD

**Issue by davidboom95** [benface/tailwindcss-gap#4]
Hello, I noticed that nested gaps does not work.
PUG CODE:
```pug
.flex.flex-column.gap.gap-y-2
 .flex.gap.gap-x-2
     span Hello
     span Hello
     span Hello
 .flex.gap.gap-x-2
     span Hello
     span Hello
     span Hello
 .flex.gap.gap-x-2
     span Hello
     span Hello
     span Hello
```
This code only apply one margin.

**Comment by benface** [comment]
Thank you for opening this issue @davidboom95. That is a known issue but I forgot to document it, so I just did here: https://github.com/benface/tailwindcss-gap#nesting-known-issue

It is caused by the fact that the `gap` classes are implemented with custom properties that have an effect on the element they're on AND their direct children. As annoying as it is, I have no plans to fix it, as the workaround is very easy and I can't think of a fix that wouldn't double – if not quadruple – the size of the generated CSS.
